server:
  port: 10086
spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      server-addr: localhost:8848
    gateway:
      routes:
        - id: user-service # 路由标识，必须唯一，名字自己起
          uri: lb://user-service # 从nacos中获取路由的目标服务
          predicates:
            - Path=/user/** # 什么请求路径路由到上面配的目标服务
          filters:
            - AddRequestParameter=zkp, jxr # 添加请求参数，zkp=jxr
#      default-filters: # 默认过滤器，对所有路由都生效
#        - AddRequestHeader=addHeader
      globalcors: # 全局的跨域处理
        add-to-simple-url-handler-mapping: true # 解决options请求被拦截问题
        corsConfigurations:
          '[/**]':
            allowedOrigins: # 允许哪些网站的跨域请求
              - "http://localhost:63342"
            allowedMethods: # 允许的跨域ajax的请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*" # 允许在请求中携带的头信息
            allowCredentials: true # 是否允许携带cookie
            maxAge: 360000 # 这次跨域检测的有效期