server:
  port: 8081
spring:
  application:
    name: pay-service

  datasource:
    url: jdbc://mysql://${db.host}:3306/payment
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${db.username}
    password: ${db.password}
  cloud:
    # 服务注册
    nacos:
      server-addr: localhost:8848