server:
  port: 8082
spring:
  application:
    name: cart-service

  datasource:
    url: jdbc://mysql://${db.host}:3306/cart
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${db.user}
    password: ${db.password}